openapi: 3.2.0
info:
  title: IDC Service Me API
  description: APIs for IDC Service.
  version: 2.4.0
  x-harvested-from: Mintlify per-page OpenAPI slices on docs.gmicloud.ai/api-reference (llms.txt index), merged 2026-10-13
servers:
- url: https://console.gmicloud.ai/api/v1
  description: IDC Service API
security: []
tags:
- name: Me
paths:
  /me/oauth/auth-tokens:
    post:
      tags:
      - Me
      summary: Create an auth token via OAuth
      description: Create a short-term authentication token using a third-party OAuth provider (e.g., Google).
      operationId: createAuthTokenOAuth
      requestBody:
        description: The request body for creating an auth token via OAuth.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOAuthAuthTokenRequest'
      responses:
        '201':
          description: Successfully created an auth token for user via OAuth.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createOAuthAuthTokenResponse'
        '400':
          description: '- [group:**oauth**, code:**0**]: Unsupported OAuth provider.

            - [group:**oauth**, code:**1**]: Invalid access token.

            - [group:**request**, code:**0**]: Invalid field in the request body.

            - [group:**request**, code:**1**]: The request body is required.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request body:
                  summary: Invalid field in the request body.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: provider
                      expression: required
                      originalValue: ''
                      reason: This field is required.
                The request body is required:
                  summary: The request body is required.
                  value:
                    group: request
                    code: 1
                    message: The request body is required.
        '404':
          description: '- [group:**user**, code:**1**]: User does not exist.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                User does not exist:
                  summary: User does not exist.
                  value:
                    group: user
                    code: 0
                    message: User does not exist.
        '500':
          description: '- [group:**oauth**, code:**1000**]: Get user info encountered error.

            - [group:**session**, code:**200**]: Failed to create auth token.

            - [group:**session**, code:**201**]: Failed to save auth token data.

            - [group:**user**, code:**1200**]: Get user encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Failed to create auth token:
                  summary: Failed to create auth token.
                  value:
                    group: session
                    code: 200
                    message: Failed to create auth token.
                    traces:
                    - error occurred.
      x-source: https://docs.gmicloud.ai/api-reference/me/create-an-auth-token-via-oauth.md
  /me/auth-tokens:
    post:
      tags:
      - Me
      summary: Create an auth token
      description: Create a short-term authentication token using user credentials for exchanging access and refresh tokens.
      operationId: createAuthToken
      requestBody:
        description: The create session request body.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createAuthTokenRequest'
      responses:
        '201':
          description: Successfully created an auth token for user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authTokenResponse'
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request body.

            - [group:**request**, code:**1**]: The request body is required.

            - [group:**session**, code:**0**]: Invalid email or password.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request body:
                  summary: Invalid field in the request body.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: email
                      expression: required
                      originalValue: ''
                      reason: This field is required.
                No request body:
                  summary: No request body.
                  value:
                    group: request
                    code: 1
                    message: The request body is required.
                Invalid email or password:
                  summary: Invalid email or password.
                  value:
                    group: session
                    code: 0
                    message: Invalid email or password.
        '429':
          description: '- [group:**rate-limit**, code:**0**]: Rate limit exceeded.

            '
          headers:
            Retry-After:
              description: The number of seconds the user should wait before retrying.
              schema:
                type: integer
                example: 300
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Rate limit exceeded:
                  summary: Rate limit exceeded.
                  value:
                    group: rate-limit
                    code: 0
                    message: Rate limit exceeded.
        '500':
          description: '- [group:**email**, code:**0**]: Failed to send email.

            - [group:**rate-limit**, code:**1**]: Failed to get rate limit configuration.

            - [group:**rate-limit**, code:**2**]: Failed to save rate limit configuration.

            - [group:**session**, code:**200**]: Failed to create auth token.

            - [group:**session**, code:**201**]: Failed to save auth token data.

            - [group:**session**, code:**204**]: Failed to create OTP code.

            - [group:**session**, code:**207**]: Unsupported OTP code delivery method.

            - [group:**user**, code:**1200**]: Get user encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Failed to create auth token:
                  summary: Failed to create auth token.
                  value:
                    group: session
                    code: 200
                    message: Failed to create auth token.
                    traces:
                    - error occurred.
      x-source: https://docs.gmicloud.ai/api-reference/me/create-an-auth-token.md
  /me/ssh-keys:
    post:
      tags:
      - Me
      summary: Create an SSH key
      description: Create an SSH public key for the current authenticated user.
      operationId: createSSHKey
      requestBody:
        description: The request body for SSH key creation.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createSSHKeyRequest'
      responses:
        '201':
          description: Successfully created an SSH key.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/createSSHKeyResponse'
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request.

            - [group:**request**, code:**1**]: The request body is required.

            - [group:**ssh-key**, code:**0**]: Invalid SSH key.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request:
                  summary: Invalid field in the request.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: sshKey
                      expression: required
                      originalValue: ''
                      reason: This field is required.
        '403':
          description: '- [group:**ssh-key**, code:**500**]: The maximum number of SSH keys per user has been reached.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                The maximum number of SSH keys per user has been reached:
                  summary: The maximum number of SSH keys per user has been reached.
                  value:
                    group: ssh-key
                    code: 500
                    message: The maximum number of SSH keys per user has been reached.
        '500':
          description: '- [group:**ssh-key**, code:**1000**]: Create SSH key encountered DB error.

            - [group:**ssh-key**, code:**1200**]: Get SSH key count encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Create SSH key encountered DB error:
                  summary: Create SSH key encountered DB error.
                  value:
                    group: ssh-key
                    code: 1000
                    message: Create SSH key encountered DB error.
                    traces:
                    - DB error occurred.
      security:
      - bearerAuth: []
      x-source: https://docs.gmicloud.ai/api-reference/me/create-an-ssh-key.md
    get:
      tags:
      - Me
      summary: List SSH keys
      description: Retrieve a list of SSH keys for the current authenticated user.
      operationId: listSSHKeys
      parameters:
      - name: name
        in: query
        schema:
          type: string
        description: Filter SSH keys by name (case-insensitive partial match).
        example: My SSH key
        x-oapi-codegen-extra-tags:
          binding: omitempty
        x-go-type-skip-optional-pointer: true
      - name: fingerprint
        in: query
        schema:
          type: string
        description: Filter SSH keys by SHA-256 fingerprint (case-insensitive partial match).
        example: AbCdEfGhIjKlMnOpQrStUvWxYz1234567890
        x-oapi-codegen-extra-tags:
          binding: omitempty
        x-go-type-skip-optional-pointer: true
      responses:
        '200':
          description: Successfully retrieved the list of SSH keys.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listSSHKeysResponse'
        '500':
          description: '- [group:**ssh-key**, code:**1201**]: Get SSH key list encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Get SSH key list encountered DB error:
                  summary: Get SSH key list encountered DB error.
                  value:
                    group: ssh-key
                    code: 1201
                    message: Get SSH key list encountered DB error.
                    traces:
                    - DB error occurred.
      security:
      - bearerAuth: []
      x-source: https://docs.gmicloud.ai/api-reference/me/list-ssh-keys.md
  /me/sessions:
    post:
      tags:
      - Me
      summary: Create session
      description: Create a login session for user.
      operationId: createSession
      parameters:
      - $ref: '#/components/parameters/clientIdParam'
      requestBody:
        description: The request body for session creation
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createSessionRequest'
      responses:
        '201':
          description: Successfully created a login session for user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionResponse'
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request body.

            - [group:**request**, code:**1**]: The request body is required.

            - [group:**auth**, code:**0**]: Invalid CE-ClientId.

            - [group:**auth**, code:**10**]: Invalid authToken.

            - [group:**session**, code:**205**]: Invalid otpCode.

            - [group:**session**, code:**206**]: Expired otpCode.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request body:
                  summary: Invalid field in the request body.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: email
                      expression: required
                      originalValue: ''
                      reason: This field is required.
        '500':
          description: '- [group:**session**, code:**202**]: Failed to get auth token data.

            - [group:**session**, code:**1**]: Failed to create access token.

            - [group:**session**, code:**2**]: Failed to create refresh token.

            - [group:**session**, code:**3**]: Failed to save session.

            - [group:**session**, code:**201**]: Failed to save auth token data.

            - [group:**session**, code:**203**]: Failed to delete auth token data.

            - [group:**organization**, code:**1200**]: Get organization grouping policy encountered error.

            - [group:**user**, code:**1401**]: Update user data encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Failed to create access token:
                  summary: Failed to create access token.
                  value:
                    group: session
                    code: 1
                    message: Failed to create access token.
                    traces:
                    - error occurred.
      x-source: https://docs.gmicloud.ai/api-reference/me/create-session.md
    patch:
      tags:
      - Me
      summary: Refresh session
      description: Refresh an existing session, which will return a new access token and refresh token.
      operationId: refreshSession
      parameters:
      - $ref: '#/components/parameters/clientIdParam'
      requestBody:
        description: The refresh session request body.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/refreshSessionRequest'
      responses:
        '200':
          description: Successfully refreshed an existing session.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sessionResponse'
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request body.

            - [group:**request**, code:**1**]: The request body is required.

            - [group:**auth**, code:**0**]: Invalid CE-ClientId.

            - [group:**auth**, code:**1**]: Invalid refreshToken.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request body:
                  summary: Invalid field in the request body.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: email
                      expression: required
                      originalValue: ''
                      reason: This field is required.
                No request body:
                  summary: No request body.
                  value:
                    group: request
                    code: 1
                    message: The request body is required.
                Invalid refreshToken:
                  summary: Invalid refreshToken.
                  value:
                    group: auth
                    code: 1
                    message: Invalid refreshToken.
        '500':
          description: '- [group:**session**, code:**1**]: Failed to create access token.

            - [group:**session**, code:**2**]: Failed to create refresh token.

            - [group:**session**, code:**3**]: Failed to save session to cache.

            - [group:**session**, code:**4**]: Failed to get session.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Failed to create access token:
                  summary: Failed to create access token.
                  value:
                    group: auth
                    code: 1000
                    message: Failed to create access token.
                    traces:
                    - error occurred.
      x-source: https://docs.gmicloud.ai/api-reference/me/refresh-session.md
  /me/ssh-keys/{sshKeyId}:
    delete:
      tags:
      - Me
      summary: Delete an SSH key
      description: 'Delete an SSH key owned by the currently authenticated user.

        - Users can only delete their own keys.'
      parameters:
      - $ref: '#/components/parameters/sshKeyIdParam'
      responses:
        '200':
          description: Successfully deleted the SSH key.
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request:
                  summary: Invalid field in the request.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: sshKeyId
                      expression: uuid
                      originalValue: sshKeyId
                      reason: Should be a valid UUID.
        '500':
          description: '- [group:**ssh-key**, code:**1600**]: Delete SSH key encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Delete SSH key encountered DB error:
                  summary: Delete SSH key encountered DB error.
                  value:
                    group: ssh-key
                    code: 1600
                    message: Delete SSH key encountered DB error.
                    traces:
                    - DB error occurred.
      security:
      - bearerAuth: []
      x-source: https://docs.gmicloud.ai/api-reference/me/delete-an-ssh-key.md
      operationId: deleteMeSshKeysBySshKeyId
      x-operation-id-source: derived
    patch:
      tags:
      - Me
      summary: Update an SSH key
      description: 'Update the name of an SSH key owned by the currently authenticated user.

        - Users can only update their own keys.'
      operationId: updateSSHKey
      parameters:
      - $ref: '#/components/parameters/sshKeyIdParam'
      requestBody:
        description: The request body for SSH key update.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateSSHKeyRequest'
      responses:
        '200':
          description: Successfully updated the SSH key.
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request.

            - [group:**request**, code:**1**]: The request body is required.

            '
        '403':
          description: '- [group:**ssh-key**, code:**501**]: The user has no permission to access the SSH key.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                The user has no permission to access the SSH key:
                  summary: The user has no permission to access the SSH key.
                  value:
                    group: ssh-key
                    code: 501
                    message: The user has no permission to access the SSH key.
        '500':
          description: '- [group:**ssh-key**, code:**1202**]: Get SSH key encountered DB error.

            - [group:**ssh-key**, code:**1400**]: Update SSH key encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Update SSH key encountered DB error:
                  summary: Update SSH key encountered DB error.
                  value:
                    group: ssh-key
                    code: 1400
                    message: Update SSH key encountered DB error.
                    traces:
                    - DB error occurred.
      security:
      - bearerAuth: []
      x-source: https://docs.gmicloud.ai/api-reference/me/update-an-ssh-key.md
  /me/2fa-verification-code:
    post:
      tags:
      - Me
      summary: Resend 2FA verification code
      description: Resend 2FA verificaion code.
      operationId: resend2FACode
      requestBody:
        description: The request body for resending 2FA code.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/resend2FACodeRequest'
      responses:
        '201':
          description: Successfully sent 2FA verification code.
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request body.

            - [group:**request**, code:**1**]: The request body is required.

            - [group:**auth**, code:**10**]: Invalid authToken.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request body:
                  summary: Invalid field in the request body.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: email
                      expression: required
                      originalValue: ''
                      reason: This field is required.
        '403':
          description: '- [group:**auth**, code:**5**]: The user has no permission to access the resource.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                The user has no permission to access the resource:
                  summary: The user has no permission to access the resource.
                  value:
                    group: auth
                    code: 5
                    message: The user has no permission to access the resource.
        '500':
          description: '- [group:**session**, code:**202**]: Failed to get auth token data.

            - [group:**session**, code:**204**]: Failed to create OTP code.

            - [group:**session**, code:**201**]: Failed to save auth token data.

            - [group:**session**, code:**207**]: Unsupported OTP code delivery method.

            - [group:**email**, code:**0**]: Failed to send email.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Failed to get auth token data:
                  summary: Failed to get auth token data.
                  value:
                    group: session
                    code: 202
                    message: Failed to get auth token data.
                    traces:
                    - error occurred.
      x-source: https://docs.gmicloud.ai/api-reference/me/resend-2fa-verification-code.md
  /me/profile:
    get:
      tags:
      - Me
      summary: Retrieve user's profile
      description: Retrieves the profile information of the current authenticated user.
      operationId: getUserProfile
      responses:
        '200':
          description: Successfully retrieved the user's profile.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getUserProfileResponse'
        '500':
          description: '- [group:**user**, code:**1200**]: Get user encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Get user encountered DB error:
                  summary: Get user encountered DB error.
                  value:
                    group: user
                    code: 1000
                    message: Get user encountered DB error.
                    traces:
                    - DB error occurred.
      security:
      - bearerAuth: []
      x-source: https://docs.gmicloud.ai/api-reference/me/retrieve-users-profile.md
    patch:
      tags:
      - Me
      summary: Update user's profile
      description: Update the current authenticated user's profile. Either **firstName** or **lastName** should be provided in the request body.
      operationId: updateUserProfile
      requestBody:
        description: The profile update request body. Either **firstName** or **lastName** should be provided.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateProfileRequest'
      responses:
        '200':
          description: Successfully updated the user's profile.
        '400':
          description: '- [group:**request**, code:**1**]: The request body is required.

            - [group:**request**, code:**0**]: Invalid field in the request body.

            - [group:**user**, code:**3**]: Either firstName or lastName must be provided in the request body.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Either firstName or lastName must be provided in the request body:
                  summary: Either firstName or lastName must be provided in the request body.
                  value:
                    group: user
                    code: 3
                    message: Either firstName or lastName must be provided in the request body.
        '500':
          description: '- [group:**user**, code:**1401**]: Update user data encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Update user data encountered DB error:
                  summary: Update user data encountered DB error.
                  value:
                    group: user
                    code: 1401
                    message: Update user data encountered DB error.
                    traces:
                    - DB error occurred.
      security:
      - bearerAuth: []
      x-source: https://docs.gmicloud.ai/api-reference/me/update-users-profile.md
  /me/password:
    patch:
      tags:
      - Me
      summary: Update user password
      description: 'Allows a user to update their password.

        - **Authenticated user**: Must use `Bearer ` in Authorization header and provide `currentPassword` in the request body.

        - **Password reset user**: Must provide `passwordResetToken` and provide `otpCode` in the request body.'
      operationId: updateUserPassword
      requestBody:
        description: The request body for updating user password
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updatePasswordRequest'
      responses:
        '200':
          description: Successfully updated user password.
        '400':
          description: '- [group:**request**, code:**0**]: Invalid field in the request.

            - [group:**request**, code:**1**]: The request body is required.

            - [group:**user**, code:**208**]: Invalid otpCode.

            - [group:**user**, code:**209**]: Expired otpCode.

            - [group:**user**, code:**211**]: Either `Authorization` in header or `passwordResetToken` in request body must be provided.

            - [group:**user**, code:**212**]: Invalid currentPassword.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid field in the request:
                  summary: Invalid field in the request.
                  value:
                    group: request
                    code: 0
                    validationDetail:
                    - field: newPassword
                      expression: required
                      originalValue: ''
                      reason: This field is required.
        '401':
          description: '- [group:**user**, code:**206**]: Invalid reset password token.

            - [group:**user**, code:**207**]: Expired reset password token.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid reset password token:
                  summary: Invalid reset password token.
                  value:
                    group: user
                    code: 11
                    message: Invalid reset password token.
        '500':
          description: '- [group:**user**, code:**1**]: User does not exist.

            - [group:**user**, code:**201**]: Get user password reset data encountered error.

            - [group:**user**, code:**210**]: Delete user password reset data encountered error.

            - [group:**user**, code:**1200**]: Get user encountered DB error.

            - [group:**user**, code:**1400**]: Update user passsword encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Get user password reset data encountered error:
                  summary: Get user password reset data encountered error.
                  value:
                    group: user
                    code: 201
                    message: Get user password reset data encountered error.
                    traces:
                    - error occurred.
      security:
      - {}
      - bearerAuth: []
      x-source: https://docs.gmicloud.ai/api-reference/me/update-user-password.md
  /me/api-keys/current:
    get:
      tags:
      - Me
      summary: Verify API Key and retrieve the key details
      description: Validate the API key from the Authorization Bearer token and return the key details.
      operationId: verifyApiKey
      responses:
        '200':
          description: Successfully verified the API key and retrieved the key details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/verifyAPIKeyResponse'
        '401':
          description: '- [group:**api-key**, code:**200**]: Invalid API key.

            - [group:**api-key**, code:**201**]: Expired API key.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Invalid API key:
                  summary: Invalid API key.
                  value:
                    group: api-key
                    code: 200
                    message: Invalid API key.
        '500':
          description: '- [group:**api-key**, code:**1201**]: Get API key encountered DB error.

            '
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrStatusMsg'
              examples:
                Get API key encountered DB error:
                  summary: Get API key encountered DB error.
                  value:
                    group: api-key
                    code: 1201
                    message: Get API key encountered DB error.
                    traces:
                    - DB error occurred.
      security:
      - bearerAPIKey: []
      x-source: https://docs.gmicloud.ai/api-reference/me/verify-api-key-and-retrieve-the-key-details.md
components:
  schemas:
    ValidationDetail:
      type: object
      properties:
        field:
          type: string
          description: The field of the request data.
          x-go-type-skip-optional-pointer: true
        expression:
          type: string
          description: The form of violation.
          x-go-type-skip-optional-pointer: true
        argument:
          type: string
          description: The number or data to support the expression.
          x-go-type-skip-optional-pointer: true
        originalValue:
          description: The original value from the request.
          x-go-type-skip-optional-pointer: true
        reason:
          type: string
          description: The reason for the validation error.
          x-go-type-skip-optional-pointer: true
      example:
      - field: fieldXXX
        expression: required
        originalValue: ''
        reason: This field is required.
    createOAuthAuthTokenResponse:
      type: object
      x-go-name: createOAuthAuthTokenResponse
      properties:
        authToken:
          type: string
          description: A temporary token issued  after the initial login step. This token is used in the create session API to exchange for access and refresh tokens.
          example: eyJhbGciOiJIUzI1NiIsInR...
      required:
      - authToken
    createSessionRequest:
      type: object
      x-go-name: createSessionRequest
      properties:
        authToken:
          type: string
          description: 'A temporary token issued by the create auth token API. This token is used in the create session API to exchange for access and refresh tokens.

            '
          example: eyJhbGciOiJIUzI1NiIsInR...
          x-oapi-codegen-extra-tags:
            binding: required
        otpCode:
          type: string
          description: '(Optional) A one-time passcode (OTP) provided by the user for native login with 2FA verification.

            - Must be a numeric code.

            - This field is required only if the `is2FARequired` field in the `POST /me/auth-tokens` API response is `true`.

            '
          example: 321673
          x-oapi-codegen-extra-tags:
            binding: omitempty,numeric
          x-go-type-skip-optional-pointer: true
      required:
      - type
      - authToken
    listSSHKeysResponse:
      type: object
      x-go-name: listSSHKeysResponse
      properties:
        keys:
          type: array
          description: A list of SSH keys.
          items:
            $ref: '#/components/schemas/sshKeyListItem'
      required:
      - keys
    updatePasswordRequest:
      type: object
      x-go-name: updatePasswordRequest
      properties:
        newPassword:
          type: string
          description: The new password.
          example: MyNewSecurePassword123!
          x-oapi-codegen-extra-tags:
            binding: required
        currentPassword:
          type: string
          description: 'The user''s current password for update password.

            - This field is only required for authenticated users.

            '
          example: OldPassword123!
          x-oapi-codegen-extra-tags:
            binding: omitempty
          x-go-type-skip-optional-pointer: true
        passwordResetToken:
          type: string
          description: 'A temporary Bearer token used for password reset authentication which is issued when a user requests a password reset.

            - This field is only required for password reset users.

            '
          example: eyJhbGciOiJIUzI1NiIsInR...
          x-oapi-codegen-extra-tags:
            binding: omitempty
          x-go-type-skip-optional-pointer: true
        otpCode:
          type: string
          description: 'A one-time passcode (OTP) for reset user password.

            - Must be a numeric code.

            - This field is only required for password reset users.

            '
          example: 321673
          x-oapi-codegen-extra-tags:
            binding: omitempty,numeric
          x-go-type-skip-optional-pointer: true
      required:
      - newPassword
    sessionResponse:
      type: object
      x-go-name: sessionResponse
      properties:
        accessToken:
          type: string
          description: The access token for API requests.
          example: eyJhbGciOiJIUzI1NiIsInR...
        refreshToken:
          type: string
          description: The refresh token for session management.
          example: eyJhbGciOiJIUzI1NiIsInR...
      required:
      - accessToken
      - refreshToken
    createOAuthAuthTokenRequest:
      type: object
      x-go-name: createOAuthAuthTokenRequest
      properties:
        provider:
          type: string
          description: 'The authentication provider used for login.

            - "google": User logs in with Google OAuth.

            - "github": User logs in with Github OAuth.

            - "hugging_face": User logs in with Hugging Face OAuth.

            '
          enum:
          - google
          - github
          - hugging_face
          example: google
          x-go-type: iamLibTypes.OAuthProvider
          x-go-type-import:
            path: us-central1-go.pkg.dev/gmi-cloud-cicd/go-dev/iam-lib-go/pkg/types
            name: iamLibTypes
          x-oapi-codegen-extra-tags:
            binding: required
        accessToken:
          type: string
          description: OAuth access token (e.g., Google).
          example: ya29.a0AfH6SMB...
          x-oapi-codegen-extra-tags:
            binding: required
      required:
      - provider
      - accessToken
    apiKeyOwnerInfo:
      type: object
      description: 'Information about the user who owns this API key

        '
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          description: The user ID.
          example: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
      required:
      - id
    updateSSHKeyRequest:
      type: object
      x-go-name: updateSSHKeyRequest
      properties:
        name:
          type: string
          description: Human-readable name for the SSH key.
          example: My Updated SSH key
          x-oapi-codegen-extra-tags:
            binding: required
      required:
      - name
    createSSHKeyRequest:
      type: object
      x-go-name: createSSHKeyRequest
      properties:
        sshKey:
          type: string
          description: 'The full SSH public key supported by OpenSSH (e.g., ssh-rsa, ssh-ed25519, ecdsa-sha2-nistp256).

            '
          example: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBn... user@host
          x-oapi-codegen-extra-tags:
            binding: required
        name:
          type: string
          description: Human-readable name for the SSH key.
          example: My SSH key
          x-oapi-codegen-extra-tags:
            binding: required
      required:
      - sshKey
      - name
    sshKeyListItem:
      type: object
      x-go-name: sshKeyListItem
      description: Information about an SSH key.
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          description: The unique identifier for the SSH key.
          example: 550e8400-e29b-41d4-a716-446655440000
        name:
          type: string
          description: The SSH key name.
          example: My SSH key
        fingerprint:
          type: string
          description: The SSH key fingerprint in SHA256 format.
          example: AbCdEfGhIjKlMnOpQrStUvWxYz1234567890
        createdAt:
          type: integer
          x-go-type: int64
          description: The UNIX timestamp in seconds when the SSH key was created (UTC).
          example: 1738812775
      required:
      - id
      - name
      - fingerprint
      - createdAt
    apiKeyInfo:
      type: object
      description: Information about the API key.
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          description: The unique identifier for the API key.
          example: 550e8400-e29b-41d4-a716-446655440000
        type:
          type: string
          deprecated: true
          x-go-type-skip-optional-pointer: true
          description: 'The API key type. This field is deprecated and will be removed in a future version.

            Use the `scope` field instead to specify the API key''s scope.

            '
          enum:
          - ie_model
          x-go-type: ceCommonLibTypes.IasAPIKeyScope
          x-go-type-import:
            path: us-central1-go.pkg.dev/gmi-cloud-cicd/go-dev/ce-common-lib-go/pkg/types
            name: ceCommonLibTypes
          example: ie_model
        scope:
          type: string
          description: The API key scope.
          enum:
          - ie_model
          - ce_resource
          x-go-type: ceCommonLibTypes.IasAPIKeyScope
          x-go-type-import:
            path: us-central1-go.pkg.dev/gmi-cloud-cicd/go-dev/ce-common-lib-go/pkg/types
            name: ceCommonLibTypes
          example: ie_model
        owner:
          $ref: '#/components/schemas/apiKeyOwnerInfo'
          type: object
      required:
      - id
      - scope
      - owner
    apiKeyOrgInfo:
      type: object
      description: 'The organization associated with the API key

        '
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          description: The organization ID.
          example: 066daf34-08e8-40fe-a384-4248bcff5842
      required:
      - id
    ErrStatusMsg:
      type: object
      properties:
        group:
          type: string
          description: API function group\n -Will be "request" if there are invalid request parameters.
          x-oapi-codegen-extra-tags:
            binding: required
        code:
          type: integer
          description: The substatus error code for the API response.
          x-oapi-codegen-extra-tags:
            binding: required
        message:
          type: string
          description: The substatus error Message for API response.
          x-go-type-skip-optional-pointer: true
        traces:
          type: array
          items:
            type: string
          description: The original error messages.
          x-go-type-skip-optional-pointer: true
        validationDetail:
          type: array
          items:
            $ref: '#/components/schemas/ValidationDetail'
          description: Returned when there are invalid request paremeters(group="request")\n List of invalid fields and the reason of error.
          x-go-type-skip-optional-pointer: true
      example:
        group: request
        code: 0
        validationDetail:
        - field: email
          expression: required
          originalValue: ''
          reason: This field is required.
      required:
      - group
      - code
    userProfileOrgInfo:
      type: object
      description: "Information about the organization the user belongs to. \nThis field is omitted if the user does not belong to any organization.\n"
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          description: The user's organization ID.
          example: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
        role:
          type: string
          enum:
          - org_owner
          - org_user
          x-go-type: ceCommonLibTypes.IasOrganizationRole
          x-go-type-import:
            path: us-central1-go.pkg.dev/gmi-cloud-cicd/go-dev/ce-common-lib-go/pkg/types
            name: ceCommonLibTypes
          description: The user's organization role.
          example: org_owner
      required:
      - id
      - role
    refreshSessionRequest:
      type: object
      x-go-name: refreshSessionRequest
      properties:
        refreshToken:
          type: string
          description: The token to refresh the session. A refresh token can only be used once.
          example: eyJhbGciOiJIUzI1NiIsInR...
          x-oapi-codegen-extra-tags:
            binding: required
      required:
      - refreshToken
    createSSHKeyResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          description: The unique identifier (UUID) of the newly created SSH key.
          example: 550e8400-e29b-41d4-a716-446655440000
          x-go-type-skip-optional-pointer: true
    createAuthTokenRequest:
      type: object
      x-go-name: createAuthTokenRequest
      properties:
        email:
          type: string
          description: 'User''s email address.

            - Must be a valid email format.

            '
          example: john_doe@example.com
          x-oapi-codegen-extra-tags:
            binding: required,email
        password:
          type: string
          description: User's password.
          example: john_doe_password
          x-oapi-codegen-extra-tags:
            binding: required
      required:
      - email
      - password
    updateProfileRequest:
      type: object
      x-go-name: updateProfileRequest
      properties:
        firstName:
          type: string
          description: The user's first name.
          example: john
          x-oapi-codegen-extra-tags:
            binding: omitempty
          x-go-type-skip-optional-pointer: true
        lastName:
          type: string
          description: The user's last name.
          example: doe
          x-oapi-codegen-extra-tags:
            binding: omitempty
          x-go-type-skip-optional-pointer: true
    authTokenResponse:
      type: object
      x-go-name: authTokenResponse
      properties:
        authToken:
          type: string
          description: A temporary token issued  after the initial login step. This token is used in the create session API to exchange for access and refresh tokens.
          example: eyJhbGciOiJIUzI1NiIsInR...
        is2FARequired:
          type: boolean
          description: Whether two-factor authentication (2FA) is required for the create session API. If `true`, the client must include an OTP code in the request body to complete the authentication.
          example: true
      required:
      - authToken
      - is2FARequired
    userProfileUserInfo:
      type: object
      description: Information about the user.
      properties:
        id:
          type: string
          format: uuid
          x-go-type: uuid.UUID
          description: The user's ID.
          example: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
        email:
          type: string
          description: The user's email address.
          example: john.doe@example.com
        firstName:
          type: string
          description: The user's first name.
          example: john
        lastName:
          type: string
          description: The user's last name.
          example: doe
        lastLoginAt:
          type: integer
          description: The UNIX timestamp in seconds (UTC) of the user's most recent login. (UTC).
          format: int64
          example: 1740557336
        lastLoginIDP:
          type: string
          description: 'The identity provider used during the user''s most recent login.

            - "native": Logged in with username and password.

            - "google": Logged in using Google OAuth.

            - "github": Logged in using GitHub OAuth.

            - "hugging_face": Logged in using Hugging Face OAuth.

            '
          enum:
          - native
          - google
          - github
          - hugging_face
          example: google
          x-go-type: iamLibTypes.OAuthProvider
          x-go-type-import:
            path: us-central1-go.pkg.dev/gmi-cloud-cicd/go-dev/iam-lib-go/pkg/types
            name: iamLibTypes
          x-oapi-codegen-extra-tags:
            binding: required
      required:
      - id
      - email
      - firstName
      - lastName
      - lastLoginAt
      - lastLoginIDP
    verifyAPIKeyResponse:
      type: object
      x-go-name: verifyAPIKeyResponse
      properties:
        key:
          $ref: '#/components/schemas/apiKeyInfo'
          type: object
        organization:
          $ref: '#/components/schemas/apiKeyOrgInfo'
          type: object
      required:
      - key
      - organization
    getUserProfileResponse:
      type: object
      x-go-name: getUserProfileResponse
      properties:
        user:
          $ref: '#/components/schemas/userProfileUserInfo'
          type: object
        organization:
          $ref: '#/components/schemas/userProfileOrgInfo'
          type: object
      required:
      - user
    resend2FACodeRequest:
      type: object
      x-go-name: resend2FACodeRequest
      properties:
        authToken:
          type: string
          description: 'A temporary token issued by the create auth token API. This token is used in the create session API to exchange for access and refresh tokens.

            '
          example: eyJhbGciOiJIUzI1NiIsInR...
          x-oapi-codegen-extra-tags:
            binding: required
      required:
      - authToken
  parameters:
    clientIdParam:
      name: CE-ClientId
      in: header
      schema:
        type: string
      required: true
      description: 'A unique identifier to each user device and browser.

        - Must be less than 8 characters.

        - Only alphanumeric characters are allowed.

        '
    sshKeyIdParam:
      name: sshKeyId
      in: path
      schema:
        type: string
        format: uuid
        x-go-type: uuid.UUID
        example: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
      required: true
      description: 'The ID of the SSH key

        - Must be a valid UUID.

        '
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "An access token used to authenticate a user and grant access to restricted APIs. It is issued by session APIs.\nFor status codes related to this header, refer to the \n[Common Headers Documentation](https://gmicloud.atlassian.net/wiki/spaces/CE/pages/47199534/Common+Headers#Authorization).\n"
    bearerAPIKey:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'An API key used to authenticate a user and grant access to restricted models. It is issued by api-keys APIs.

        '
    bearerEmailVerificationToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'A token used to verify the validity of an email address.

        It must be included in the Authorization header when verifying the email address.

        '
